POST http://localhost:3000/teachers HTTP/1.1
Content-Type: application/json

{"name":"Mehmet","email":"mehmet@gmail.com","password":"12345"}

###

POST http://localhost:3000/teachers/5fe78c5b4537fa13ac66f54d/createQuestions HTTP/1.1
Content-Type: application/json

{"who":"deneme1","where":"deneme1","when":"deneme1","why":"deneme1","what":"deneme1","how":"deneme1"}

###

POST http://localhost:3000/teachers/5fe78c5b4537fa13ac66f54d/viewNews HTTP/1.1
Content-Type: application/json

{"newsId":"5fe79575e6fdb8217807ab99","grade":"10","comment":"deneme"}


###

POST  http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{"name":"Gökçe","email":"gokce@gmail.com","password":"12345"}

###

POST  http://localhost:3000/students/5fe7946699773a1be4554d8a/createNews HTTP/1.1
Content-Type: application/json

{"questionsId":"5fe78e0a99773a1be4554d88","newsText":"deneme"}
